image: docker:18.09.7

stages:
  - build
  - deploy_staging
  - deploy_production

variables:
  CONTAINER: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  #DOCKER_HOST: tcp://localhost:2375

services:
  - docker:dind

build:
  stage: build
  script:

    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CONTAINER" .
    - docker push "$CONTAINER"

  retry: 2
  only:
    - master

deploy-application-staging:
  stage: deploy_staging
  image: devth/helm:v3.0.2
  script:
    - echo "Deploying to ${CI_ENVIRONMENT_NAME}"
    - helm upgrade
      --install
      --kubeconfig $KUBECONFIG_STAGING
      --set web.name="ris-${CI_COMMIT_REF_SLUG}"
      --set web.container=$CONTAINER
      --set env.name=${CI_ENVIRONMENT_NAME}
      --set env.url=${CI_ENVIRONMENT_URL}
      --set env.domain=cs.s.cda.gov.ph
      --set env.tls=staging-tls
      --set env.tls_issuer=staging-issuer
      --set db.hostname=$DB_HOSTNAME
      --set db.username=$DB_USERNAME
      --set db.password=$DB_PASSWORD
      --set db.database=$DB_DATABASE
      cs
      ./.chart/application
  environment:
    name: staging
    url: https://cs.s.cda.gov.ph
  only:
    - master

deploy-database-staging:
  when: manual
  stage: deploy_staging
  image: devth/helm:v3.0.2
  script:
    - echo "Deploying to ${CI_ENVIRONMENT_NAME}"
    - helm install
      --kubeconfig $KUBECONFIG_STAGING
      database
      ./.chart/database
  environment:
    name: staging
    url: http://202.90.136.155
  only:
    - master

deploy-application-production:
  when: manual
  stage: deploy_production
  image: devth/helm:v3.0.2
  script:
    - echo "Deploying to production"
    - helm upgrade
      --install
      --kubeconfig $KUBECONFIG_PRODUCTION
      --set web.name="ris-${CI_COMMIT_REF_SLUG}"
      --set web.container=$CONTAINER
      --set env.name=${CI_ENVIRONMENT_NAME}
      --set env.url=${CI_ENVIRONMENT_URL}
      --set env.domain=cs.cda.gov.ph
      --set env.tls=cda-tls
      --set db.hostname=$DB_HOSTNAME
      --set db.username=$DB_USERNAME
      --set db.password=$DB_PASSWORD
      --set db.database=$DB_DATABASE
      cs
      ./.chart/application
  environment:
    name: production
    url: https://cs.cda.gov.ph
  only:
    - master

deploy-database-production:
  when: manual
  stage: deploy_production
  image: devth/helm:v3.0.2
  script:
    - echo "Deploying to production"
    - helm install
      --kubeconfig $KUBECONFIG_PRODUCTION
      database
      ./.chart/database
  environment:
    name: production
    url: http://202.90.136.156
  only:
    - master