version: "3.7"
services:
  app-php:
    build: 
      context: .
    volumes:
      - app:/srv/site
    networks:
      - internal
  app-nginx:
    image: nginx:1.16-alpine
    volumes:
      - app:/srv/site
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - internal
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: main
    volumes:
      #- ./DB:/docker-entrypoint-initdb.d
      - ./.database:/var/lib/mysql
    networks:
      - internal
    ports:
      - "33060:3306"
volumes:
  app:
networks:
  internal:
    