version: "3.7"
services:
  app-php:
    build: 
      context: .
    volumes:
      - type: bind
        source: .
        target: /srv/site
        volume:
          nocopy: true
      - type: bind
        source: ./.shared-volume
        target: /var/www/shared-volume
        volume:
          nocopy: true
      - tmp:/tmp
    networks:
      - internal
    links:
      - database
      - messaging
    env_file: .env
  app-nginx:
    image: nginx:1.16-alpine
    volumes:
      - type: bind
        source: .
        target: /srv/site
        volume:
          nocopy: true
      - type: bind
        source: ./.shared-volume
        target: /var/www/shared-volume
        volume:
          nocopy: true
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - internal
    links:
      - app-php
  database:
    image: mysql:8
    env_file: .env
    volumes:
      #- ./DB:/docker-entrypoint-initdb.d
      - ./.database:/var/lib/mysql
    networks:
      - internal
    ports:
      - "33060:3306"
  messaging:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    env_file: .env
    networks:
      - internal
  app-php-background:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /srv/site
        volume:
          nocopy: true
      - type: bind
        source: ./.shared-volume
        target: /var/www/shared-volume
        volume:
          nocopy: true
      - tmp:/tmp
    networks:
      - internal
    links:
      - messaging
    command: "php /srv/site/messaging/consumer.php"
volumes:
  tmp:
networks:
  internal: