kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.web.name }}-cm
data:
  nginx.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      
      # Set nginx to serve files from the shared volume!
      root /var/www/html;
      server_name _;
      location / {
        include  /etc/nginx/mime.types;
        try_files $uri /index.php?$query_string;
      }

      location /uploads {
        root /var/www/shared-volume;
      }

      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
      }
    }