apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}-deployment
  labels:
      app: {{ .Values.web.name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      volumes:
        # Create the shared files volume to be used in both pods
        - name: shared-files
          emptyDir: {}
        
        # Add the ConfigMap we declared above as a volume for the pod
        - name: nginx-config-volume
          configMap:
            name: {{ .Values.web.name }}-cm
      containers:
      - env:
        - name: DB_HOSTNAME
          value: {{ .Values.db.hostname }}
        - name: DB_USERNAME
          value: {{ .Values.db.username }}
        - name: DB_PASSWORD
          value: {{ .Values.db.password }}
        - name: DB_DATABASE
          value: {{ .Values.db.database }}
        - name: ENVIRONMENT_URL
          value: {{ .Values.env.url }}
        image: {{ .Values.web.container }}
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        imagePullPolicy: Always
        name: php
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
        #command: ["/bin/sh"]
        #args: ["-c", "/bin/sh /srv/site/post-start.sh && php-fpm"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /srv/site/. /var/www/html"]
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
      - image: nginx:1.7.9
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /liveliness.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1 
        readinessProbe:
          httpGet:
            path: /readiness.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 3
      nodeSelector:
        type: application
      {{ if eq .Values.env.name "staging" }}
      imagePullSecrets:
       - name: {{ .Values.deploy.gitlab.key }}
      {{ end }}
      restartPolicy: Always