apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.web.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    {{ if not (eq .Values.env.tls_issuer "none") }}
    cert-manager.io/issuer: {{ .Values.env.tls_issuer }}
    {{ end }}
spec:
  {{ if not (eq .Values.env.tls "none") }}
  tls:
  - hosts:
      - {{ .Values.env.domain }}
    secretName: {{ .Values.env.tls }}
  {{ end }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.web.name }}-service
          servicePort: 80
    {{ if not (eq .Values.env.domain "none") }}
    host: {{ .Values.env.domain }}
    {{ end }}
    #host: cs.cda.gov.ph #will have this when domain have been updated