apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.web.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "604800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "604800"
spec:
  tls:
  - hosts:
    - ris.cda.gov.ph
    secretName: cda-ssl
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.web.name }}-service
          servicePort: http
    #host: cs.cda.gov.ph #will have this when domain have been updated